### ISSUE TITLE
Weeks 7-8

### ISSUE THREAD

**Issue by lc512k** [lc512k/jl-node-app#5]
- [x] wrap up DB work - `res.render` a different message if the user already exists. Watch out for order of execution with the callback
- [x] building a new page (template) to display a list of headlines
- [x] building the endpoint on the server that's going to `res.render` those headlines
- [x] getting set up with the dev api
- [x] calling the headlines endpoint from the server

Additional tasks you could do:
- [x] styling that page
- [ ] experiment with pagination. Have a look at how FT do it (https://www.ft.com/world?format=&page=2) and what it would entail, front end and back end wise to accomplish it.

**Comment by j-mes** [comment]
Hi!

A few things that came up while starting on this task and I had additional questions on:

1. Storing and using env values i.e. API key.

I had a little dig around to see what would be the best way of doing this. A lot of the answers I found used a library i.e. JWT, [Passport.js](http://www.passportjs.org/) and [dotenv](https://github.com/scottmotte/dotenv). I watched a video where Wes Bos covered dotenv. 

I'm curious about what is your method of doing this part? I looked and thought the library dotenv was pretty nice, and I found out that it was also advocated by the Twelve-Factor app, which I am also reading through bit by bit at a time. I will use the Heroku environment vars for the app online, I was wondering regarding local development.

2. Handlebars with foreach on the headline item. 

I assume I can put a foreach to iterate through the headlines and to populate inside res.render? I put in a partial template where I can have the headline item values inside a normal template i.e. headlines which would just have the following:

``` html
<ul class="headlines">
    {{> headlineItem }}
</ul>
```
I'll see if I can put the code up later as a PR so that you can review and I can make the changes. At this point I can't get this working.

**Comment by lc512k** [comment]
We use different things for env vars, but dotenv has been used more recently in internal products and it's worked out quite well

Re handlebars, if I understood correctly it sounds good :) Can surely tell you more when the PR is in
